version: "3.5"
services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=bed_core
    ports:
      - "5467:5432"
    networks:
      - api_network
    volumes:
      - database_flux:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    ports:
      - "5050:80"
    networks:
      - api_network
    restart: unless-stopped

  main-redis:
    image: 'redis:7-alpine'
    ports:
      - "6379:6379"
    restart: always
    networks:
      - api_network
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1045:1025" # SMTP server
      - "8045:8025" # Web UI
    networks:
      - api_network

networks:
  api_network:
    driver: bridge

volumes:
  database_flux:
  pgadmin:
  redis_data:
  redis_test_data:
