// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	ActivateUser(ctx context.Context, arg ActivateUserParams) error
	ChangeUserName(ctx context.Context, arg ChangeUserNameParams) error
	ChangeUserPassword(ctx context.Context, arg ChangeUserPasswordParams) error
	ChangeUserPin(ctx context.Context, arg ChangeUserPinParams) (sql.NullString, error)
	ChangeUserVerifyCode(ctx context.Context, arg ChangeUserVerifyCodeParams) (sql.NullString, error)
	CreateCPasswordResetToken(ctx context.Context, arg CreateCPasswordResetTokenParams) (PasswordResetToken, error)
	CreateLogin2faToken(ctx context.Context, arg CreateLogin2faTokenParams) (Login2fatoken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error)
	DeleteLogin2faToken(ctx context.Context, token string) error
	DeletePasswordResetToken(ctx context.Context, token string) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetLogin2faToken(ctx context.Context, token string) (Login2fatoken, error)
	GetPasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error)
	GetPasswordResetTokenByUserID(ctx context.Context, userID uuid.UUID) (PasswordResetToken, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserProfile(ctx context.Context, id uuid.UUID) (UserProfile, error)
	GetUserProfileByUserID(ctx context.Context, userID uuid.UUID) (UserProfile, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error)
	UpdateRegistrationStatus(ctx context.Context, arg UpdateRegistrationStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UserEnableMfa(ctx context.Context, arg UserEnableMfaParams) error
}

var _ Querier = (*Queries)(nil)
